### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by villnoweric** [PredatorsRobotics/MeetStatusScreen#4]
Add settings page to allow dashboard users to edit team settings.

**Settings**
- Team Number
- City
- State
- Weather Unit

_Consider_
- Making settings a JSON file.

**Comment by ChandlerSwift** [comment]
Something like this should work to allow writing to a file.

``` php
/* Code for file - settings */
$config = '<?php 
$dbhost = "'. $_POST["dbhost"]. '";
$dbuname = "'. $_POST["dbuname"]. '";
$dbpass = "'. $_POST["dbpass"]. '";
$dbname = "'. $_POST["dbname"]. '";
?>';

/* Write Variables to file */
$fp = fopen("../includes/config.php", "w");
fwrite($fp, $config);
fclose($fp);
include_once "../includes/config.php" ;
```

**Comment by villnoweric** [comment]
Thank you Chandler. Completed settings page and added border if its your team.
